// -----------------------------------------------
// BOSS Related Descriptions
// -----------------------------------------------

/** Internal Name of Mob (Used in Configurator) */
export const BossInternalNameTooltip: Record<string, string> = {
  internalName: "YAMLファイル内でこのMobを識別するための一意のID。他のMobや設定から参照される際に使用します。",
};

/** 1. Boss: Options */
export const BossOptionsTooltips: Record<string, string> = {
  Type: "MobのベースとなるMinecraftエンティティ。（例: ZOMBIE, SKELETON, CREEPER）",
  Display: "ゲーム内で表示されるMobの名前。カラーコードが使用可能です。（例: '&cAngry Mob'）",
  Health: "Mobの体力。",
  Damage: "Mobが与えるダメージ。設定しない場合、ベースエンティティのデフォルト値が使用されます。",
  Armor: "Mobの防御力。",
  FollowRange: "Mobがプレイヤーを認識し、追跡を開始する距離（ブロック単位）。",
  KnockbackResistance: "ノックバックへの耐性。0.0（耐性なし）から 1.0（完全耐性）の間で設定。",
  MovementSpeed: "Mobの移動速度。0.2が標準速度です。",
  MaxCombatDistance: "Mobがターゲットとの戦闘を継続する最大距離。これを超えると戦闘を停止し、元の場所に戻ろうとします。",
  AttackSpeed: "Mobの攻撃速度。秒間の攻撃回数。（例: 0.5 = 2秒に1回）",
  Collidable: "プレイヤーや他のエンティティと衝突判定を持つか。",
  Despawn: "Mobがデスポーン（自然消滅）するかどうか。'true' (通常通り), 'false' (しない), 'scripted' (スクリプトでのみデスポーン可)",
  Faction: "Mobが所属する派閥。同じ派閥のMobは互いに攻撃しません。",
  Invincible: "Mobを無敵にするかどうか。ダメージを受けなくなります。",
  Interactable: "プレイヤーがこのMobを右クリックで操作（例: 村人との取引）できるか。",
  Levitation: "Mobが浮遊するかどうか。",
  Mount: "このMobが騎乗する別のMythicMobのInternalName。",
  Mountable: "プレイヤーがこのMobに騎乗できるか。",
  NoAI: "MobのAIを無効化するか。棒立ちになります。",
  NoDamageTicks: "ダメージを受けた後の無敵時間（ティック単位）。",
  NoGravity: "Mobに重力が適用されなくなるか。",
  Persistent: "Mobがデスポーンしなくなるか。'Despawn: false' と似ていますが、ワールドアンロード/ロード後も保持されます。",
  PreventOtherDrops: "ベースエンティティ（例: ゾンビの腐肉）のドロップを無効化するか。",
  PreventSunburn: "Mobが日光で燃えるのを防ぐか。",
  PreventItemPickup: "Mobが地面のアイテムを拾うのを防ぐか。",
  PreventRandomEquipment: "Mobがランダムな装備を持ってスポーンするのを防ぐか。",
  PreventRenaming: "名札などでMobの名前が変更されるのを防ぐか。",
  PreventSlimeSplit: "スライムがダメージを受けたときに分裂するのを防ぐか。",
  PreventPotionEffects: "Mobがポーション効果を受けるのを防ぐか。",
  PreventTeleporting: "Mobが（エンダーマンのように）テレポートするのを防ぐか。",
  PreventWorldSave: "ワールドセーブ時にこのMobが保存されるのを防ぐか。サーバー再起動で消えます。",
  RepeatAllSkills: "スキルがクールダウン後に自動的に繰り返されるか。",
  ShowHealth: "Mobの頭上に体力バーを表示するか。（古いオプション）",
  Silent: "Mobのサウンド（鳴き声、足音）を無効化するか。",
  SpectatorTarget: "スペクテイターモードのプレイヤーがこのMobをターゲット（右クリックで視点変更）できるか。",
  ThreatTable: "このMobが脅威テーブル（ヘイトリスト）を使用するか。AI Target Selector に影響します。",
  UsePlayerName: "Mobの表示名に、スポーンさせたプレイヤーの名前を使用するか。",
  CanPickUpItems: "Mobがアイテムを拾えるか。(5.0.0+)",
  CanSpawn: "Mobが自然湧きするか（条件が満たされた場合）。(5.0.0+)",
  Experience: "Mobが倒されたときにドロップする経験値量。(5.0.0+)",
  Level: "Mobのレベル。スケーリングやスキルの条件分岐に使用できます。(5.0.0+)",
  Glowing: "Mobを発光させるか。(5.1.0+)",
  Gravity: "Mobに重力を適用するか（NoGravityの逆）。(5.1.0+)",
  HasArms: "アーマースタンドの腕を表示するか。(5.1.0+)",
  HasBasePlate: "アーマースタンドの台座を表示するか。(5.1.0+)",
  HasGravity: "アーマースタンドに重力を適用するか。(5.1.0+)",
  Invisible: "Mobを透明にするか。(5.1.0+)",
  IsBaby: "Mobを子供の姿にするか。(5.1.0+)",
  IsMarker: "アーマースタンドをマーカー（当たり判定なし）にするか。(5.1.0+)",
  IsSmall: "アーマースタンドを小さいサイズにするか。(5.1.0+)",
  IsVisible: "アーマースタンドの体を表示するか。(5.1.0+)",
  NoClip: "Mobがブロックをすり抜けるか。(5.1.0+)",
  Pitch: "Mobの顔の上下の向き（ピッチ）。(5.1.0+)",
  Scale: "Mobのサイズ（倍率）。(5.1.0+)",
  ShowArmor: "アーマースタンドの装備を表示するか。(5.1.0+)",
  Sitting: "Mobを座った状態にするか。(5.1.0+)",
  SlimeSize: "スライムのサイズ。(5.1.0+)",
  Yaw: "Mobの体の向き（ヨー）。(5.1.0+)",
  AIName: "使用するカスタムAIプロファイルのID。(5.2.0+)",
  CreeperCharged: "クリーパーを帯電状態（匠）にするか。",
  CreeperExplosionRadius: "クリーパーの爆発半径。",
  CreeperFuse: "クリーパーが爆発するまでの時間（ティック）。",
  CreeperIncendiary: "クリーパーの爆発で火災が発生するか。",
  CreeperMaxFuse: "クリーパーの最大信管時間。",
  CreeperPowered: "CreeperCharged と同じです。",
  EnderDragonPhase: "エンダードラゴンの行動フェーズを指定します。",
  EndermanHeldBlock: "エンダーマンが持つブロックのID。（例: STONE）",
  FoxType: "キツネのタイプ。（例: RED, SNOW）",
  Gene: "パンダの遺伝子（性格）。（例: NORMAL, LAZY, PLAYFUL）",
  HasCollision: "Collidable と同じです。",
  HorseArmor: "馬の鎧の強さ。",
  HorseColor: "馬の色。",
  HorseStyle: "馬の模様。",
  OcelotType: "ヤマネコのタイプ。",
  ParrotVariant: "オウムの色。",
  RabbitType: "ウサギのタイプ。",
  Sheared: "羊の毛が刈られた状態か。",
  VillagerProfession: "村人の職業。",
  VillagerType: "村人のバイオームタイプ。（例: PLAINS, DESERT）",
  WitchHeldItem: "魔女が手に持つアイテムのID。",
  WolfAngry: "狼が怒っている状態か。",
  WolfCollarColor: "狼の首輪の色。（例: RED, BLUE）",
  YawPitchLock: "Mobの向きを固定するか。",
  Pose: "エンティティのポーズ。（例: SLEEPING, SWIMMING）",
  MainHand: "ヴェックス（Vex）が右手に持つアイテムのID。",
  ApplyInvisibility: "透明ポーションのエフェクトを適用するか（Invisible: true とは異なる）。",
};

/** 2. Boss: DisplayOptions */
export const BossDisplayTooltips: Record<string, string> = {
  NameVisible: "Mobの名前が常に表示されるか（カーソルを合わせなくても）。",
  HealthVisible: "Mobの体力が常に表示されるか（カーソルを合わせなくても）。",
  ShowHealth: "HealthVisible と同じです。",
  Glowing: "Mobを発光させるか。",
  Invisible: "Mobを透明にするか。",
  Invulnerable: "Mobを無敵にするか。",
  HasBoundingBox: "Mobの当たり判定（バウンディングボックス）を表示するか（デバッグ用）。",
  Model: "ModelEngineプラグインで使用するモデルのID。",
  MythicCrater: "MythicCraterプラグインで使用するクレーターのID。",
  ShowPitch: "Mobのピッチ（上下の向き）を名前タグに表示するか（デバッグ用）。",
};

/** 3. Boss: Equipment */
export const BossEquipmentTooltips: Record<string, string> = {
  Equipment: "Mobに装備させるアイテムのリスト。\nフォーマット: [InternalItemName]:[SLOT]\nスロット: HAND, OFFHAND, HEAD, CHEST, LEGS, FEET, 0-8 (インベントリ)",
};

/** 4. Boss: BossBar */
export const BossBarTooltips: Record<string, string> = {
  Enabled: "ボスバーを有効にするか。",
  Title: "ボスバーに表示するタイトル。",
  Range: "プレイヤーがボスバーを視認できる最大距離。",
  Color: "ボスバーの色。",
  Style: "ボスバーのスタイル（線の区切り方）。",
  CreateFog: "ボスバー表示時に霧を発生させるか（エンダードラゴン戦のように）。",
  DarkenSky: "ボスバー表示時に空を暗くするか（ウィザー戦のように）。",
  PlayMusic: "ボスバー表示時にボス戦の音楽を再生するか。",
};

/** 5. Boss: Custom AI */
export const BossAITooltips: Record<string, string> = {
  AIGoalSelectors: "Mobの「行動」AI。優先度順にリストします。（例: 1:randomstroll, 2:stareatplayer）",
  AITargetSelectors: "Mobの「ターゲット」AI。優先度順にリストします。（例: 1:players, 2:clear）",
};

/** 7. Boss: KillMessages */
export const BossKillMessagesTooltips: Record<string, string> = {
  KillMessages: "このMobがプレイヤーを倒したときに表示されるメッセージのリスト。ランダムで1つ選ばれます。\nプレースホルダー: <target.name>, <mob.name>",
};

/** 8. Boss: ImmunityTables */
export const BossImmunityTooltips: Record<string, string> = {
  ImmunityTables: "特定のダメージタイプに対する耐性（倍率）を設定します。\nフォーマット: [DamageType]:[Multiplier]\n（例: FIRE:0 (炎無効), FALL:1 (通常), EXPLOSION:2 (2倍ダメージ)）",
};

/** 9. Boss: Disguise */
export const BossDisguiseTooltips: Record<string, string> = {
  Type: "変装するエンティティのタイプ。（例: PLAYER, ZOMBIE, ARMOR_STAND, FALLING_BLOCK）",
  Skin: "PLAYER変装時に使用するスキン。（プレイヤー名またはURL）",
  Burning: "変装体が燃えているように見せるか。",
  Blocking: "変装体がブロックしている（盾を構えている）ように見せるか。",
  Invisible: "変装体を透明にするか。",
  ShowName: "変装体の名前を表示するか。",
  Sneaking: "変装体がスニークしているように見せるか。",
  Sprinting: "変装体がスプリントしているように見せるか。",
  ArrowCount: "変装体に刺さっている矢の数を設定します。",
  ArmorStandInvisible: "アーマースタンド変装時に、本体を透明にするか。",
  ArmorStandMarker: "アーマースタンド変装時に、マーカー（当たり判定なし）にするか。",
  ArmorStandBasePlate: "アーマースタンド変装時に、台座を表示するか。",
  ArmorStandArms: "アーマースタンド変装時に、腕を表示するか。",
  ArmorStandSmall: "アーマースタンド変装時に、小さいサイズにするか。",
  BatHanging: "コウモリ変装時に、ぶら下がっている状態にするか。",
  CreeperPowered: "クリーパー変装時に、帯電状態にするか。",
  CreeperIgnited: "クリーパー変装時に、爆発直前の状態にするか。",
  EndermanBlock: "エンダーマン変装時に、持っているブロックのID。",
  EndermanBlockData: "エンダーマン変装時に、持っているブロックのデータ値（レガシー）。",
  GhastAggressive: "ガスト変装時に、攻撃的な状態（目が赤く）にするか。",
  GuardianElderly: "ガーディアン変装時に、エルダーガーディアンにするか。",
  HorseColor: "馬変装時の色。",
  HorseStyle: "馬変装時の模様。",
  HorseChest: "馬変装時に、チェストを付けているか。",
  HorseSaddled: "馬変装時に、鞍を付けているか。",
  HorseArmor: "馬変装時の鎧のタイプ。（例: IRON, GOLD, DIAMOND）",
  IronGolemLPlayerCreated: "アイアンゴーレム変装時に、プレイヤーが作成した（攻撃してこない）状態にするか。",
  OcelotType: "ヤマネコ変装時のタイプ。",
  PigSaddled: "豚変装時に、鞍を付けているか。",
  RabbitType: "ウサギ変装時のタイプ。",
  SheepColor: "羊変装時の色。",
  SheepSheared: "羊変装時に、毛が刈られた状態にするか。",
  SlimeSize: "スライム変装時のサイズ。",
  MagmaClientSize: "マグマキューブ変装時のサイズ。",
  SnowmanDerp: "スノーゴーレム変装時に、カボチャを外した状態にするか。",
  VillagerProfession: "村人変装時の職業。",
  WolfAngry: "狼変装時に、怒っている状態にするか。",
  WolfSitting: "狼変装時に、座っている状態にするか。",
  WolfCollarColor: "狼変装時の首輪の色。",
  ZombieType: "ゾンビ変装時のタイプ。（例: HUSK, DROWNED）",
  ZombieVillagerProfession: "ゾンビ村人変装時の職業。",
  ZombieBaby: "ゾンビ変装時に、子供にするか。",
  ZombieConversion: "ゾンビ村人が治療中（ぶるぶる震える）の状態にするか。",
  EntityHorse: "（古いオプション）馬変装を使用するか。",
  Item: "FALLING_BLOCK や ITEM 変装時に使用するアイテムID。",
  ItemData: "（レガシー）アイテムのデータ値。",
  ItemAmount: "ITEM 変装時のアイテム数。",
  AnimalColor: "（新しいバージョン）動物の色。",
  CatType: "猫変装時のタイプ。",
  FoxType: "キツネ変装時のタイプ。",
  MooshroomType: "ムーシュルーム変装時のタイプ。（例: RED, BROWN）",
  PandaGene: "パンダ変装時の遺伝子。",
  ParrotVariant: "オウム変装時の色。",
  PufferFishState: "フグ変装時の膨らみ具合。",
  TropicalFishType: "熱帯魚変装時のタイプ。",
  Pose: "エンティティ変装時のポーズ。",
  ModifyBoundingBox: "変装に合わせて当たり判定を変更するか。",
};


// -----------------------------------------------
//  Mob Types
// -----------------------------------------------

/**
 * Mob Type List
 * Used in BossOptions.tsx
 */
export const mobTypeOptions = [
  { value: "ALLAY", label: "ALLAY" },
  { value: "ARMOR_STAND", label: "ARMOR_STAND" },
  { value: "AXOLOTL", label: "AXOLOTL" },
  { value: "BAT", label: "BAT" },
  { value: "BEE", label: "BEE" },
  { value: "BLAZE", label: "BLAZE" },
  { value: "BOAT", label: "BOAT" },
  { value: "CAMEL", label: "CAMEL" },
  { value: "CAT", label: "CAT" },
  { value: "CAVE_SPIDER", label: "CAVE_SPIDER" },
  { value: "CHEST_BOAT", label: "CHEST_BOAT" },
  { value: "CHEST_MINECART", label: "CHEST_MINECART" },
  { value: "CHICKEN", label: "CHICKEN" },
  { value: "COD", label: "COD" },
  { value: "COMMAND_BLOCK_MINECART", label: "COMMAND_BLOCK_MINECART" },
  { value: "COW", label: "COW" },
  { value: "CREEPER", label: "CREEPER" },
  { value: "DOLPHIN", label: "DOLPHIN" },
  { value: "DONKEY", label: "DONKEY" },
  { value: "DROWNED", label: "DROWNED" },
  { value: "EGG", label: "EGG" },
  { value: "ELDER_GUARDIAN", label: "ELDER_GUARDIAN" },
  { value: "ENDER_CRYSTAL", label: "ENDER_CRYSTAL" },
  { value: "ENDER_DRAGON", label: "ENDER_DRAGON" },
  { value: "ENDER_PEARL", label: "ENDER_PEARL" },
  { value: "ENDER_SIGNAL", label: "ENDER_SIGNAL" },
  { value: "ENDERMAN", label: "ENDERMAN" },
  { value: "ENDERMITE", label: "ENDERMITE" },
  { value: "EVOKER", label: "EVOKER" },
  { value: "EVOKER_FANGS", label: "EVOKER_FANGS" },
  { value: "EXPERIENCE_BOTTLE", label: "EXPERIENCE_BOTTLE" },
  { value: "EXPERIENCE_ORB", label: "EXPERIENCE_ORB" },
  { value: "FALLING_BLOCK", label: "FALLING_BLOCK" },
  { value: "FIREBALL", label: "FIREBALL" },
  { value: "FIREWORK_ROCKET", label: "FIREWORK_ROCKET" },
  { value: "FOX", label: "FOX" },
  { value: "FROG", label: "FROG" },
  { value: "FURNACE_MINECART", label: "FURNACE_MINECART" },
  { value: "GHAST", label: "GHAST" },
  { value: "GIANT", label: "GIANT" },
  { value: "GLOW_ITEM_FRAME", label: "GLOW_ITEM_FRAME" },
  { value: "GLOW_SQUID", label: "GLOW_SQUID" },
  { value: "GOAT", label: "GOAT" },
  { value: "GUARDIAN", label: "GUARDIAN" },
  { value: "HOGLIN", label: "HOGLIN" },
  { value: "HOPPER_MINECART", label: "HOPPER_MINECART" },
  { value: "HORSE", label: "HORSE" },
  { value: "HUSK", label: "HUSK" },
  { value: "ILLUSIONER", label: "ILLUSIONER" },
  { value: "IRON_GOLEM", label: "IRON_GOLEM" },
  { value: "ITEM", label: "ITEM" },
  { value: "ITEM_FRAME", label: "ITEM_FRAME" },
  { value: "LEASH_KNOT", label: "LEASH_KNOT" },
  { value: "LIGHTNING_BOLT", label: "LIGHTNING_BOLT" },
  { value: "LLAMA", label: "LLAMA" },
  { value: "LLAMA_SPIT", label: "LLAMA_SPIT" },
  { value: "MAGMA_CUBE", label: "MAGMA_CUBE" },
  { value: "MARKER", label: "MARKER" },
  { value: "MINECART", label: "MINECART" },
  { value: "MOOSHROOM", label: "MOOSHROOM" },
  { value: "MULE", label: "MULE" },
  { value: "OCELOT", label: "OCELOT" },
  { value: "PAINTING", label: "PAINTING" },
  { value: "PANDA", label: "PANDA" },
  { value: "PARROT", label: "PARROT" },
  { value: "PHANTOM", label: "PHANTOM" },
  { value: "PIG", label: "PIG" },
  { value: "PIGLIN", label: "PIGLIN" },
  { value: "PIGLIN_BRUTE", label: "PIGLIN_BRUTE" },
  { value: "PILLAGER", label: "PILLAGER" },
  { value: "PLAYER", label: "PLAYER" },
  { value: "POLAR_BEAR", label: "POLAR_BEAR" },
  { value: "POTION", label: "POTION" },
  { value: "PUFFERFISH", label: "PUFFERFISH" },
  { value: "RABBIT", label: "RABBIT" },
  { value: "RAVAGER", label: "RAVAGER" },
  { value: "SALMON", label: "SALMON" },
  { value: "SHEEP", label: "SHEEP" },
  { value: "SHULKER", label: "SHULKER" },
  { value: "SHULKER_BULLET", label: "SHULKER_BULLET" },
  { value: "SILVERFISH", label: "SILVERFISH" },
  { value: "SKELETON", label: "SKELETON" },
  { value: "SKELETON_HORSE", label: "SKELETON_HORSE" },
  { value: "SLIME", label: "SLIME" },
  { value: "SMALL_FIREBALL", label: "SMALL_FIREBALL" },
  { value: "SNIFFER", label: "SNIFFER" },
  { value: "SNOW_GOLEM", label: "SNOW_GOLEM" },
  { value: "SPAWNER_MINECART", label: "SPAWNER_MINECART" },
  { value: "SPECTRAL_ARROW", label: "SPECTRAL_ARROW" },
  { value: "SPIDER", label: "SPIDER" },
  { value: "SQUID", label: "SQUID" },
  { value: "STRAY", label: "STRAY" },
  { value: "STRIDER", label: "STRIDER" },
  { value: "TADPOLE", label: "TADPOLE" },
  { value: "TNT", label: "TNT" },
  { value: "TNT_MINECART", label: "TNT_MINECART" },
  { value: "TRADER_LLAMA", label: "TRADER_LLAMA" },
  { value: "TRIDENT", label: "TRIDENT" },
  { value: "TROPICAL_FISH", label: "TROPICAL_FISH" },
  { value: "TURTLE", label: "TURTLE" },
  { value: "VEX", label: "VEX" },
  { value: "VILLAGER", label: "VILLAGER" },
  { value: "VINDICATOR", label: "VINDICATOR" },
  { value: "WANDERING_TRADER", label: "WANDERING_TRADER" },
  { value: "WARDEN", label: "WARDEN" },
  { value: "WITCH", label: "WITCH" },
  { value: "WITHER", label: "WITHER" },
  { value: "WITHER_SKELETON", label: "WITHER_SKELETON" },
  { value: "WITHER_SKULL", label: "WITHER_SKULL" },
  { value: "WOLF", label: "WOLF" },
  { value: "ZOGLIN", label: "ZOGLIN" },
  { value: "ZOMBIE", label: "ZOMBIE" },
  { value: "ZOMBIE_HORSE", label: "ZOMBIE_HORSE" },
  { value: "ZOMBIE_VILLAGER", label: "ZOMBIE_VILLAGER" },
  { value: "ZOMBIFIED_PIGLIN", label: "ZOMBIFIED_PIGLIN" }
];

/**
 * Mob Type Map of Mob types and their Japanese translations (for DocsPage)
 */
export const MobTypesTooltips: Record<string, string> = {
  "ALLAY": "アレイ",
  "ARMOR_STAND": "防具立て",
  "AXOLOTL": "ウーパールーパー",
  "BAT": "コウモリ",
  "BEE": "ミツバチ",
  "BLAZE": "ブレイズ",
  "BOAT": "ボート",
  "CAMEL": "ラクダ",
  "CAT": "ネコ",
  "CAVE_SPIDER": "洞窟グモ",
  "CHEST_BOAT": "チェスト付きボート",
  "CHEST_MINECART": "チェスト付きトロッコ",
  "CHICKEN": "ニワトリ",
  "COD": "タラ",
  "COMMAND_BLOCK_MINECART": "コマンドブロック付きトロッコ",
  "COW": "ウシ",
  "CREEPER": "クリーパー",
  "DOLPHIN": "イルカ",
  "DONKEY": "ロバ",
  "DROWNED": "ドラウンド",
  "EGG": "卵（投げられた）",
  "ELDER_GUARDIAN": "エルダーガーディアン",
  "ENDER_CRYSTAL": "エンドクリスタル",
  "ENDER_DRAGON": "エンダードラゴン",
  "ENDER_PEARL": "エンダーパール（投げられた）",
  "ENDER_SIGNAL": "エンダーアイ（投げられた）",
  "ENDERMAN": "エンダーマン",
  "ENDERMITE": "エンダーマイト",
  "EVOKER": "喚起者",
  "EVOKER_FANGS": "喚起者の牙",
  "EXPERIENCE_BOTTLE": "経験値ボトル（投げられた）",
  "EXPERIENCE_ORB": "経験値オーブ",
  "FALLING_BLOCK": "落下中のブロック",
  "FIREBALL": "火の玉（ガスト）",
  "FIREWORK_ROCKET": "花火",
  "FOX": "キツネ",
  "FROG": "カエル",
  "FURNACE_MINECART": "かまど付きトロッコ",
  "GHAST": "ガスト",
  "GIANT": "ジャイアント",
  "GLOW_ITEM_FRAME": "輝く額縁",
  "GLOW_SQUID": "ヒカリイカ",
  "GOAT": "ヤギ",
  "GUARDIAN": "ガーディアン",
  "HOGLIN": "ホグリン",
  "HOPPER_MINECART": "ホッパー付きトロッコ",
  "HORSE": "ウマ",
  "HUSK": "ハスク",
  "ILLUSIONER": "イリュ―ジョナー",
  "IRON_GOLEM": "アイアンゴーレム",
  "ITEM": "ドロップアイテム",
  "ITEM_FRAME": "額縁",
  "LEASH_KNOT": "リードの結び目",
  "LIGHTNING_BOLT": "雷",
  "LLAMA": "ラマ",
  "LLAMA_SPIT": "ラマの唾",
  "MAGMA_CUBE": "マグマキューブ",
  "MARKER": "マーカー（エンティティ）",
  "MINECART": "トロッコ",
  "MOOSHROOM": "ムーシュルーム",
  "MULE": "ラバ",
  "OCELOT": "ヤマネコ",
  "PAINTING": "絵画",
  "PANDA": "パンダ",
  "PARROT": "オウム",
  "PHANTOM": "ファントム",
  "PIG": "ブタ",
  "PIGLIN": "ピグリン",
  "PIGLIN_BRUTE": "ピグリンブルート",
  "PILLAGER": "ピリジャー",
  "PLAYER": "プレイヤー",
  "POLAR_BEAR": "シロクマ",
  "POTION": "スプラッシュポーション（投げられた）",
  "PUFFERFISH": "フグ",
  "RABBIT": "ウサギ",
  "RAVAGER": "ラヴェジャー",
  "SALMON": "サケ",
  "SHEEP": "ヒツジ",
  "SHULKER": "シュルカー",
  "SHULKER_BULLET": "シュルカーの弾",
  "SILVERFISH": "シルバーフィッシュ",
  "SKELETON": "スケルトン",
  "SKELETON_HORSE": "スケルトンホース",
  "SLIME": "スライム",
  "SMALL_FIREBALL": "小さな火の玉（ブレイズ）",
  "SNIFFER": "スニッファー",
  "SNOW_GOLEM": "スノーゴーレム",
  "SPAWNER_MINECART": "スポナー付きトロッコ",
  "SPECTRAL_ARROW": "光の矢",
  "SPIDER": "クモ",
  "SQUID": "イカ",
  "STRAY": "ストレイ",
  "STRIDER": "ストライダー",
  "TADPOLE": "オタマジャクシ",
  "TNT": "着火したTNT",
  "TNT_MINECART": "TNT付きトロッコ",
  "TRADER_LLAMA": "行商人のラマ",
  "TRIDENT": "トライデント（投げられた）",
  "TROPICAL_FISH": "熱帯魚",
  "TURTLE": "カメ",
  "VEX": "ヴェックス",
  "VILLAGER": "村人",
  "VINDICATOR": "ヴィンディケーター",
  "WANDERING_TRADER": "行商人",
  "WARDEN": "ウォーデン",
  "WITCH": "ウィッチ",
  "WITHER": "ウィザー",
  "WITHER_SKELETON": "ウィザースケルトン",
  "WITHER_SKULL": "ウィザーの頭蓋骨",
  "WOLF": "オオカミ",
  "ZOGLIN": "ゾグリン",
  "ZOMBIE": "ゾンビ",
  "ZOMBIE_HORSE": "ゾンビホース",
  "ZOMBIE_VILLAGER": "ゾンビ村人",
  "ZOMBIFIED_PIGLIN": "ゾイドピグリン"
};


// -----------------------------------------------
// ITEM Related Descriptions
// -----------------------------------------------

/** Internal Name of Item (Used in Configurator) */
export const ItemInternalNameTooltip: Record<string, string> = {
  internalName: "YAMLファイル内でこのアイテムを識別するための一意のID。Mobの装備やドロップなどで使用します。",
};

/** 1. Item: Options */
export const ItemOptionsTooltips: Record<string, string> = {
  Id: "ベースとなるMinecraftアイテムのID。（例: DIAMOND_SWORD, STONE, PLAYER_HEAD）",
  Amount: "アイテムの数量。",
  Data: "（レガシー）アイテムのデータ値。主に色付き羊毛などに使用されました。",
  Damage: "ツールの耐久値（ダメージ）。設定しない場合、新品になります。",
  Lore: "アイテムの説明文。カラーコードが使用可能です。1行ずつリストに追加します。",
  Unbreakable: "アイテムが壊れなくなる（耐久値が減らなくなる）かどうか。",
  CustomModelData: "リソースパックで使用するカスタムモデルデータ（テクスチャ）のID。",
  EnchantmentGlint: "エンチャントされていないアイテムに、エンチャントの輝き（エフェクト）を付けるか。'AUTO', 'true', 'false' が指定可能。",
  Texture: "PLAYER_HEAD（プレイヤーヘッド）に使用するテクスチャのBase64文字列。",
  PotionColor: "ポーションアイテムの色をRGB値で指定します。（例: 255,0,0）",
  Player: "PLAYER_HEAD に使用するスキンのプレイヤー名。（Textureより優先度が低い）",
  Hide: "アイテムの情報を隠すためのフラグ。'ATTRIBUTES', 'ENCHANTS', 'LORE', 'UNBREAKABLE' など。",
  ItemFlags: "Hide と同じです。ItemFlags の方がより新しいフラグに対応している場合があります。",
  BannerLayers: "バナーの模様を定義します。1行ずつリストに追加します。",
  "Book.Title": "本のタイトル。",
  "Book.Author": "本の著者。",
  "Book.Pages": "本の内容。1ページずつリストに追加します。",
  "Firework.Power": "花火の飛距離（0-3）。",
  "Firework.Flicker": "花火がチカチカと点滅するか。",
  "Firework.Trail": "花火が尾を引くか。",
  "Firework.Type": "花火の形状。",
  "Firework.Colors": "花火の基本色。RGB値をリストに追加します。（例: 255,0,0）",
  "Firework.FadeColors": "花火が消えるときの色。RGB値をリストに追加します。",
  "Map.Color": "地図の色をRGB値で指定します。",
  "Map.Downscale": "地図の縮尺を変更するか。",
  "Map.Locked": "地図をロック（更新不可）するか。",
  "Map.Location": "地図の中心座標を指定します。（例: world,100,64,-200）",
  "Map.MapID": "既存の地図のIDを指定します。",
};

/** 2. Item: Attributes */
export const ItemAttributesTooltips: Record<string, string> = {
  Attributes: "アイテムに付与する属性（ステータス）補正。\nフォーマット: [SLOT]:[AttributeType]:[Amount]:[Operation]\nスロット: HAND, OFFHAND, HEAD, CHEST, LEGS, FEET\n属性: GENERIC_MAX_HEALTH, GENERIC_ATTACK_DAMAGE など\n操作: 0 (加算), 1 (乗算), 2 (乗算)",
};

/** 3. Item: Enchantments */
export const ItemEnchantmentsTooltips: Record<string, string> = {
  Enchantments: "アイテムに付与するエンチャント。\nフォーマット: [EnchantmentName]:[Level]\n（例: DAMAGE_ALL:5, PROTECTION_FIRE:4）",
};

/** 4. Item: Potions */
export const ItemPotionsTooltips: Record<string, string> = {
  Potions: "ポーションアイテムに付与するポーション効果。\nフォーマット: [EffectName]:[DurationTicks]:[Amplifier]\n（例: SPEED:600:0 (スピードI, 30秒)）",
};


// -----------------------------------------------
// DOCS Page Data Structure
// -----------------------------------------------

/** Data structure used in DocsPage.tsx */
export const docData = {
  boss: [
    { name: 'Internal Name', data: BossInternalNameTooltip },
    { name: 'Mob Types', data: MobTypesTooltips }, 
    { name: 'Options', data: BossOptionsTooltips },
    { name: 'Display', data: BossDisplayTooltips },
    { name: 'Equipment', data: BossEquipmentTooltips },
    { name: 'BossBar', data: BossBarTooltips },
    { name: 'Custom AI', data: BossAITooltips },
    { name: 'Kill Messages', data: BossKillMessagesTooltips },
    { name: 'Immunity', data: BossImmunityTooltips },
    { name: 'Disguise', data: BossDisguiseTooltips },
  ],
  item: [
    { name: 'Internal Name', data: ItemInternalNameTooltip },
    { name: 'Options', data: ItemOptionsTooltips },
    { name: 'Attributes', data: ItemAttributesTooltips },
    { name: 'Enchantments', data: ItemEnchantmentsTooltips },
    { name: 'Potions', data: ItemPotionsTooltips },
  ]
};

/** Full data list used in LocalSearchBot.tsx */
export const allDocEntries = [
  ...docData.boss.flatMap(cat => 
    Object.entries(cat.data).map(([key, value]) => ({ 
      type: 'Boss', 
      category: cat.name, 
      option: key, 
      description: cat.name === 'Mob Types' ? `${key} - ${value}` : value
    }))
  ),
  ...docData.item.flatMap(cat => 
    Object.entries(cat.data).map(([key, value]) => ({ 
      type: 'Item', 
      category: cat.name, 
      option: key, 
      description: value 
    }))
  ),
];